version: '3'
services:
  mymongo:
    image: mongo:3.6
  web:
    # build: .
    image: vignesh405/payconstructcodechallenge:latest
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mymongo:27017/test 
     - BASE_URL=http://localhost:8080
     - NODE_ENV=production
    links:
     - mymongo 
    depends_on: 
     - mymongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     